version: '3.9'
services:
  limesurvey:
    image: martialblog/limesurvey:latest
    env_file: settings.env
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.limesurvey-http.rule=Host(`survey.cssnr.com`)
        - traefik.http.routers.limesurvey-http.entrypoints=http
        - traefik.http.routers.limesurvey-http.middlewares=https-redirect
        - traefik.http.routers.limesurvey-https.rule=Host(`survey.cssnr.com`)
        - traefik.http.routers.limesurvey-https.entrypoints=https
        - traefik.http.routers.limesurvey-https.tls=true
        - traefik.http.services.limesurvey.loadbalancer.server.port=80
        - traefik.http.services.limesurvey.loadbalancer.server.scheme=http
    volumes:
      - lime_data:/var/www/html/upload/surveys
    networks:
      - traefik-public

volumes:
  lime_data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=test01.cssnr.com,nolock,rw
      device: ":/data/docker/limesurvey"

networks:
  traefik-public:
    external: true
